### ISSUE TITLE
Ядро BQ 2400L Voice 20 

### ISSUE THREAD

**Issue by AXKuhta** [HenriDellal/generic-kernels-code#1]
Здравствуйте! Хочу спросить, получалось ли у кого-нибудь собрать работающее ядро под BQ 2400L?

Я пытался собрать ядро из этого дерева: https://github.com/yonglongliu/kernel, дополнив его файлами из https://github.com/yonglongliu/vendor, используя конфиг sprd_sharkle_fp_defconfig и гугловский GCC 4.9.

Ядро собирается, и вроде бы даже как-то стартует (Подсветка экрана тускнеет, телефон обнаруживается как USB устройство), но до рабочего стола оно не догружается и бутанимацию не показывает.

**Comment by HenriDellal** [comment]
Здравствуйте.
Ядро, собранное для pmOS мной и протестированное другим человеком, имело ту же проблему.

У меня этого устройства нет, но могу предположить, что послужило причиной.

1. Неправильное использование dts. Файл из этого репозитория нужно переименовать в `sp9820e-1h10-native.dts` и заменить соответствующий файл в исходниках ядра.
2. Неполный конфиг ядра. Кроме основного конфига есть ещё и наборы изменений для отдельных платформ, которые находятся в https://github.com/yonglongliu/kernel/tree/master/sprd-diffconfig/sharkle/arm . Нужно использовать файлы aarch32_user_diff_config и mocor5_diff_config

**Comment by AXKuhta** [comment]
Получилось всё-таки доковылять до загрузки!

![Запустилось](https://i.imgur.com/pAh90ZW.jpg)

Решающим стал костыль для отключения проверки версии модулей:

```diff
diff --git a/kernel/module.c b/kernel/module.c
index b14a4f31..c70165f9 100644
--- a/kernel/module.c
+++ b/kernel/module.c
@@ -1324,7 +1324,7 @@ static int check_version(Elf_Shdr *sechdrs,
 bad_version:
        pr_warn("%s: disagrees about version of symbol %s\n",
               mod->name, symname);
-       return 0;
+       return 1;
 }

 static inline int check_modstruct_version(Elf_Shdr *sechdrs,
@@ -2871,7 +2871,7 @@ static int check_modinfo(struct module *mod, struct load_info *info, int flags)
                modmagic = NULL;

        /* This is allowed: modprobe --force will invalidate it. */
-       if (!modmagic) {
+       /* if (!modmagic) {
                err = try_to_force_load(mod, "bad vermagic");
                if (err)
                        return err;
@@ -2879,7 +2879,7 @@ static int check_modinfo(struct module *mod, struct load_info *info, int flags)
                pr_err("%s: version magic '%s' should be '%s'\n",
                       mod->name, modmagic, vermagic);
                return -ENOEXEC;
-       }
+       } */

        if (!get_modinfo(info, "intree"))
                add_taint_module(mod, TAINT_OOT_MODULE, LOCKDEP_STILL_OK);
```

```diff
diff --git a/kernel/module.c b/kernel/module.c
index c70165f9..f48b3ada 100644
--- a/kernel/module.c
+++ b/kernel/module.c
@@ -1261,7 +1261,7 @@ static struct module_attribute *modinfo_attrs[] = {

 static const char vermagic[] = VERMAGIC_STRING;

-static int try_to_force_load(struct module *mod, const char *reason)
+/* static int try_to_force_load(struct module *mod, const char *reason)
 {
 #ifdef CONFIG_MODULE_FORCE_LOAD
        if (!test_taint(TAINT_FORCED_MODULE))
@@ -1271,7 +1271,7 @@ static int try_to_force_load(struct module *mod, const char *reason)
 #else
        return -ENOEXEC;
 #endif
-}
+} */

 #ifdef CONFIG_MODVERSIONS
 /* If the arch applies (non-zero) relocations to kernel kcrctab, unapply it. */
@@ -2865,7 +2865,7 @@ static struct module *setup_load_info(struct load_info *info, int flags)
 static int check_modinfo(struct module *mod, struct load_info *info, int flags)
 {
        const char *modmagic = get_modinfo(info, "vermagic");
-       int err;
+       /* int err; */

        if (flags & MODULE_INIT_IGNORE_VERMAGIC)
                modmagic = NULL;
```

Насколько я понимаю, оно не могло подргузить mali.ko без этого.

Дефконфиг был получен следующим образом:
 - Взять sprd_sharkle_fp_defconfig
 - Вручную применить mocor5_diff_config (Всё что DEF: удаляется напрочь, всё что ADD: добавляется как =y)
 - Вручную применить aarch32_user_diff_config
 - Вручную применить trusty_aarch32_diff_config
 - Вручную применить kaios_diff_config

Это даст образ, достаточно похожий на стоковый.

Затем я начал выравнивать таблицу символов между стоковым образом и новым образом. Эта таблица находится ближе к концу файла, выглядит как огромный блок из строк с нулл-терминаторами. Можно вытащить обе таблицы, заменить все \0 на \r\n, прогнать через diff, и искать пропавшие/появившееся символы в исходниках ядра через  `grep -r --include "*" "СТРОКА" .` Взглянув на исходники, можно понять, какой конфиг нужно включить/выключить чтобы этот символ появился/исчез.

Всё ещё осталось несколько несостыковок относительно стокового ядра, но видимо они не критичны.

Вот мой дефконфиг: https://gist.github.com/AXKuhta/630d1b0df72cb286ceb5aed21b60febe

**Comment by AXKuhta** [comment]
Вот всё ядро со всеми внешними файлами и скриптами для сборки: https://github.com/AXKuhta/android_kernel_bq_2400l
